### ISSUE TITLE
Horizontal scaling support

### ISSUE THREAD

**Issue by L3o-pold** [soketi/charts#13]
The helm chart do not seems to handle horizontal scaling.
Following the https://docs.soketi.app/advanced-usage/horizontal-scaling/clustering documentation, I used the following env vars.

```yaml
env:
- name: PORT
  value: "6001"
- name: MODE
  value: full
- name: CLUSTER_PORT
  value: "11002"
- name: SOKETI_DEBUG
  value: "1"
- name: ADAPTER_DRIVER
  value: cluster
```

I ended with 3 nodes that were elected master with the following logs:

```shell
soketi-66bfb59674-wmnxg soketi [Fri Mar 04 2022 22:44:16 GMT+0000 (Coordinated Universal Time)] Promoted from node to master.
soketi-66bfb59674-wmnxg soketi {
soketi-66bfb59674-wmnxg soketi   isMaster: true,
soketi-66bfb59674-wmnxg soketi   isMasterEligible: true,
soketi-66bfb59674-wmnxg soketi   weight: -0.1646433855526,
soketi-66bfb59674-wmnxg soketi   address: '127.0.0.1',
soketi-66bfb59674-wmnxg soketi   advertisement: undefined
soketi-66bfb59674-wmnxg soketi }
```

Is it normal or a configuration issue on my side or a known issue? Message are not always broadcaster to client, depending on which node is connected the client.
