### ISSUE TITLE
How do you specify your .env values?

### ISSUE THREAD

**Issue by asdbnasd2OPasd** [soketi/charts#37]
Sorry for probably missing something really obvious - but how do you do the setup the values?

I can see the avilable variables here: https://docs.soketi.app/app-management/array-driver

But when installing with helm, how do I pass SOKETI_DEFAULT_APP_ID, SOKETI_DEFAULT_APP_KEY, SOKETI_DEFAULT_APP_SECRET? Thanks

TIA

**Comment by maxvisser** [comment]
The helm cli example did not work for me as the deployment does not contain any setting for the env variabled.

Did this instead; I added it from a secret which I already created for my laravel app in k8s:
values.yaml
```yaml
app:
  extraEnv:
      - name: SOKETI_DEFAULT_APP_ID
        valueFrom:
          secretKeyRef:
            name: app-env-secrets
            key: PUSHER_APP_ID
      - name: SOKETI_DEFAULT_APP_KEY
        valueFrom:
          secretKeyRef:
            name: app-env-secrets
            key: PUSHER_APP_KEY
      - name: SOKETI_DEFAULT_APP_SECRET
        valueFrom:
          secretKeyRef:
            name: app-env-secrets
            key: PUSHER_APP_SECRET
```
